name: "install kuori"
description: "install kuori"

runs:
  using: "composite"
  steps:
    - name: Download latest kuori binary using gh CLI
      shell: bash
      run: |
        gh release download --repo wim-web/kuori --pattern 'kuori-x86_64-unknown-linux-*'

        mv kuori ${{ github.workspace }}/bin
        chmod +x ${{ github.workspace }}/bin/kuori
        echo ${{ github.workspace }}/bin >> $GITHUB_PATH
      env:
        GH_TOKEN: ${{ github.token }}
