name: install test
on:
  pull_request:
    
    
jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: wim-web/kuori/.github/actions/install@install_action
      


      - run: kuori
