name: install test
on:
  pull_request:

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ./.github/actions/install
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host-name: ${{ secrets.SSH_HOST_NAME }}
          ssh-user: ${{ secrets.SSH_USER }}
      - run: type kuori
