name: Release
on:
  push:
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Cross compile for ${{ matrix.target }}
        run: cross build --release
        
      - run: ./kuori

      # - name: Upload release binary
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.target }}-binary
      #     path: target/${{ matrix.target }}/release/your-binary-name
      

      