name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: cargo build
        run: |
          cargo build --release
          mv target/release/kuori kuori-x86_64-unknown-linux-gnu
        
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} \
            target/release/kuori#kuori-x86_64-unknown-linux-gnu \
            --title "Release ${{ github.ref }}"
